apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minecraft-controller.fullname" . }}-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "minecraft-controller.fullname" . }}-role
rules:
  - apiGroups: ["", "apps", "networking.k8s.io"]
    resources: ["deployments", "services", "pods", "endpoints", "persistentvolumeclaims", "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "minecraft-controller.fullname" . }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "minecraft-controller.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "minecraft-controller.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io